// Sample listings shown only while the database has no real products.
// Delete this file (and its script tag) once real producers are on the site.

const SAMPLE_PRODUCTS = [
  { id: 's1', name: 'Kampot Black Pepper', name_km: 'ម្រេចខ្មៅកំពត', region_name: 'Kampot', region_name_km: 'កំពត', price_usd_min: 12, price_usd_max: 18, price_khr_min: 48700, price_khr_max: 73000, price_min: 12, price_max: 18, currency: 'USD', unit: 'kg', average_rating: 4.9, review_count: 32, seller_verified: true, is_boosted: true, cover_image_path: 'assets/images/categories/spices-seasonings.png' },
  { id: 's2', name: 'Cambodia Sesame Oil', name_km: 'ប្រេងល្ងកម្ពុជា', region_name: 'Kampong Cham', region_name_km: 'កំពង់ចាម', price_usd_min: 6.16, price_usd_max: 6.16, price_khr_min: 25000, price_khr_max: 25000, price_min: 25000, price_max: 25000, currency: 'KHR', unit: 'bottle', average_rating: 4.8, review_count: 10, seller_verified: true, is_boosted: true, cover_image_path: 'assets/images/categories/beverages.png' },
  { id: 's3', name: 'Palm Sugar', name_km: 'ស្ករត្នោត', region_name: 'Kampong Speu', region_name_km: 'កំពង់ស្ពឺ', price_usd_min: 3, price_usd_max: 4, price_khr_min: 12200, price_khr_max: 16200, price_min: 3, price_max: 4, currency: 'USD', unit: 'kg', average_rating: 4.7, review_count: 21, seller_verified: true, is_boosted: true, cover_image_path: 'assets/images/categories/bread-bakery.png' },
  { id: 's4', name: 'Mondulkiri Wild Honey', name_km: 'ទឹកឃ្មុំព្រៃមណ្ឌលគិរី', region_name: 'Mondulkiri', region_name_km: 'មណ្ឌលគិរី', price_usd_min: 15, price_usd_max: 15, price_khr_min: 60900, price_khr_max: 60900, price_min: 15, price_max: 15, currency: 'USD', unit: 'litre', average_rating: 4.6, review_count: 8, seller_verified: true, is_boosted: false, cover_image_path: 'assets/images/categories/beverages.png' },
  { id: 's5', name: 'Battambang Jasmine Rice', name_km: 'អង្ករម្លិះបាត់ដំបង', region_name: 'Battambang', region_name_km: 'បាត់ដំបង', price_usd_min: 1.2, price_usd_max: 1.5, price_khr_min: 4900, price_khr_max: 6100, price_min: 1.2, price_max: 1.5, currency: 'USD', unit: 'kg', average_rating: 4.9, review_count: 45, seller_verified: true, is_boosted: false, cover_image_path: 'assets/images/categories/raw-materials.png' },
  { id: 's6', name: 'Dried Mango Slices', name_km: 'ស្វាយក្រៀម', region_name: 'Kandal', region_name_km: 'កណ្ដាល', price_usd_min: 1.48, price_usd_max: 1.97, price_khr_min: 6000, price_khr_max: 8000, price_min: 6000, price_max: 8000, currency: 'KHR', unit: 'pack', average_rating: 4.5, review_count: 14, seller_verified: false, is_boosted: false, cover_image_path: 'assets/images/categories/snacks.png' },
  { id: 's7', name: 'Handwoven Rattan Basket', name_km: 'កញ្ជើផ្តៅត្បាញដោយដៃ', region_name: 'Siem Reap', region_name_km: 'សៀមរាប', price_usd_min: 8, price_usd_max: 20, price_khr_min: 32500, price_khr_max: 81100, price_min: 8, price_max: 20, currency: 'USD', unit: 'piece', average_rating: 4.8, review_count: 19, seller_verified: true, is_boosted: false, cover_image_path: 'assets/images/categories/arts-crafts.png' },
  { id: 's8', name: 'Kampot Durian', name_km: 'ធុរេនកំពត', region_name: 'Kampot', region_name_km: 'កំពត', price_usd_min: 5, price_usd_max: 9, price_khr_min: 20300, price_khr_max: 36500, price_min: 5, price_max: 9, currency: 'USD', unit: 'kg', average_rating: 4.4, review_count: 6, seller_verified: true, is_boosted: true, cover_image_path: 'assets/images/categories/fruits-vegetables.png' },
];

const SAMPLE_REQUESTS = [
  { id: 'r1', title: 'Battambang Natural Peanuts', quantity_min: 2000, quantity_max: 4000, quantity_unit: 'kg', deadline: '2026-10-23', urgency: 'URGENT', region_names: ['Kandal', 'Battambang'], image_paths: ['assets/images/categories/snacks.png'], business: { business_name: 'Midas King of Food Cambodia', region_name: 'Phnom Penh', verification_status: 'VERIFIED' }, rating: 4.9 },
  { id: 'r2', title: '1L HDPE Plastic Bottles', quantity_min: 5000, quantity_max: 5000, quantity_unit: 'pieces', deadline: '2026-11-10', urgency: 'NORMAL', region_names: [], image_paths: ['assets/images/categories/industrial-goods.png'], business: { business_name: 'Pich Auto Fluids', region_name: 'Phnom Penh', verification_status: 'VERIFIED' }, rating: 4.7 },
  { id: 'r3', title: 'Fresh Cashew Nuts', quantity_min: 1000, quantity_max: 1500, quantity_unit: 'kg', deadline: '2026-11-30', urgency: 'NORMAL', region_names: ['Kampong Thom', 'Mondulkiri'], image_paths: ['assets/images/categories/raw-materials.png'], business: { business_name: 'Angkor Snack Factory', region_name: 'Kampong Cham', verification_status: 'VERIFIED' }, rating: 4.6 },
  { id: 'r4', title: 'Organic Lemongrass', quantity_min: 300, quantity_max: 500, quantity_unit: 'kg', deadline: null, urgency: 'NORMAL', region_names: ['Takeo'], image_paths: ['assets/images/categories/spices-seasonings.png'], business: { business_name: 'Sovann Tea House', region_name: 'Siem Reap', verification_status: 'VERIFIED' }, rating: 4.8 },
];

const SAMPLE_PRODUCERS = [
  { id: 'p1', business_name: 'KIRUM Kampot Pepper Farm', region_name: 'Kampot', established_year: 2012, product_count: 6, rating: 4.9, cover_path: 'assets/images/banners/banner-1.jpg', farm_story: 'A family farm growing Kampot pepper the traditional way, sun dried and hand sorted. Every harvest is traceable back to the vines it came from.' },
  { id: 'p2', business_name: 'Sokha Palm Sugar Cooperative', region_name: 'Kampong Speu', established_year: 2015, product_count: 3, rating: 4.7, cover_path: 'assets/images/banners/banner-4.jpg', farm_story: 'Twenty village families who climb sugar palms every morning and cook the sap over wood fires, with no additives or preservatives.' },
];
